import {
  faFacebook,
  faInstagram,
  faSoundcloud,
  faSpotify,
  faTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'
import { faGlobe } from '@fortawesome/free-solid-svg-icons'

const NEXT_PUBLIC_BASE_API_URL = process.env.NEXT_PUBLIC_BASE_API_URL
const NEXT_PUBLIC_SPOTIFY_CLIENT_ID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID
const NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
const NEXT_PUBLIC_WEBSITE_URL = process.env.NEXT_PUBLIC_WEBSITE_URL

export const COLORS = {
  'primary-blue': {
    DEFAULT: '#1980F5',
    dark: '#126ED8',
  },
  'primary-green': {
    DEFAULT: '#08A881',
  },
  'primary-yellow': {
    DEFAULT: '#EEB739',
  },
  'primary-magenta': {
    DEFAULT: '#C93FC0',
  },
}

export const URLS = {
  API_URL: NEXT_PUBLIC_BASE_API_URL,
}

export const SPOTIFY_CREDENTIALS = {
  STATE_KEY: 'spotify_auth_state',
  CLIENT_ID: NEXT_PUBLIC_SPOTIFY_CLIENT_ID,
  CLIENT_SECRET: NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET,
  REDIRECT_URI: `${NEXT_PUBLIC_WEBSITE_URL}/api/spotify/callback`,
  CONNECT_REDIRECT_URI: `${NEXT_PUBLIC_WEBSITE_URL}/api/spotify/app-connect-callback`,
}

export enum SocialMediaAccounts {
  FACEBOOK = 'facebook',
  SOUNDCLOUD = 'soundCloud',
  YOUTUBE = 'youtube',
  INSTAGRAM = 'instagram',
  SPOTIFY = 'spotify',
  WEBSITE = 'website',
  TWITTER = 'twitter',
}

export const genres_values = [
  {
    label: 'Genres',
    options: [
      { label: 'Big Room', value: 'big room' },
      { label: 'Brostep', value: 'brostep' },
      { label: 'Chillstep', value: 'chillstep' },
      { label: 'EDM', value: 'edm' },
      { label: 'Future Bass', value: 'future bass' },
      { label: 'Hardstyle', value: 'hardstyle' },
      { label: 'Melbourne Bounce', value: 'melbourne bounce' },
      { label: 'Moombahton', value: 'moombahton' },
      { label: 'Psytrance', value: 'psytrance' },
      {
        label: 'Slap House / Brazilian Bass',
        value: 'slap house / brazilian bass',
      },
      { label: 'Trance', value: 'trance' },
      { label: 'Trap (EDM)', value: 'trap (edm)' },
      { label: 'Tropical House', value: 'tropical house' },
      { label: 'UK / Happy Hardcore', value: 'uk / happy hardcore' },
      { label: 'Breakbeat', value: 'breakbeat' },
      { label: 'Chiptune', value: 'chiptune' },
      { label: 'Dubstep', value: 'dubstep' },
      { label: 'Electro', value: 'electro' },
      { label: 'Electro Swing', value: 'electro swing' },
      { label: 'Electronica', value: 'electronica' },
      { label: 'Future / UK Garage', value: 'future / uk garage' },
      { label: 'Ghettotech', value: 'ghettotech' },
      { label: 'Glitch Hop', value: 'glitch hop' },
      { label: 'Heavy Drum & Bass', value: 'heavy drum & bass' },
      { label: 'Juke / Footwork', value: 'juke / footwork' },
      { label: 'Jungle', value: 'jungle' },
      { label: 'Light Drum & Bass', value: 'light drum & bass' },
      { label: 'Mainline Drum & Bass', value: 'mainline drum & bass' },
      { label: 'Riddim / Tearout', value: 'riddim / tearout' },
      { label: 'Vapor Twitch', value: 'vapor twitch' },
      { label: 'Acoustic', value: 'acoustic' },
      { label: 'Alt Country ', value: 'alt country ' },
      { label: 'Americana', value: 'americana' },
      { label: 'Bluegrass', value: 'bluegrass' },
      { label: 'Chamber Pop', value: 'chamber pop' },
      { label: 'Country', value: 'country' },
      { label: 'Folk', value: 'folk' },
      { label: 'Folk rock', value: 'folk rock' },
      { label: 'Folktronica', value: 'folktronica' },
      { label: 'Indie Folk', value: 'indie folk' },
      { label: 'Neofolk', value: 'neofolk' },
      {
        label: 'Psychedelic / Freak Folk',
        value: 'psychedelic / freak folk',
      },
      { label: 'Singer Songwriter', value: 'singer songwriter' },
      { label: 'Twee', value: 'twee' },
      { label: 'Alternative Hip-Hop', value: 'alternative hip-hop' },
      { label: 'Autotune', value: 'autotune' },
      {
        label: 'Cloud Hop / Emo Hip-Hop',
        value: 'cloud hop / emo hip-hop',
      },
      { label: 'Deutschrap', value: 'deutschrap' },
      { label: 'Drill', value: 'drill' },
      { label: 'French Hip-Hop', value: 'french hip-hop' },
      { label: 'Gangsta Rap', value: 'gangsta rap' },
      { label: 'Grime', value: 'grime' },
      {
        label: 'Hip-Hop / Conscious Hip-Hop',
        value: 'hip-hop / conscious hip-hop',
      },
      {
        label: 'Horrorcore / Trap Metal',
        value: 'horrorcore / trap metal',
      },
      { label: 'Instrumental Hip-Hop', value: 'instrumental hip-hop' },
      { label: 'International Hip-Hop', value: 'international hip-hop' },
      { label: 'Latin Hip-Hop', value: 'latin hip-hop' },
      { label: 'Lo-fi Hip-Hop', value: 'lo-fi hip-hop' },
      { label: 'Old-school Hip-Hop', value: 'old-school hip-hop' },
      { label: 'Phonk', value: 'phonk' },
      { label: 'Rap', value: 'rap' },
      {
        label: 'Study beats / Jazz-hop / Chill-hop',
        value: 'study beats / jazz-hop / chill-hop',
      },
      { label: 'Trap (Hip-hop)', value: 'trap (hip-hop)' },
      { label: 'UK Hip-Hop', value: 'uk hip-hop' },
      { label: 'Acid House', value: 'acid house' },
      { label: 'Acid Techno', value: 'acid techno' },
      { label: 'Amapiano', value: 'amapiano' },
      {
        label: 'Bass House / Electro House',
        value: 'bass house / electro house',
      },
      { label: 'Deep House', value: 'deep house' },
      { label: 'French / Filter House', value: 'french / filter house' },
      { label: 'Future House', value: 'future house' },
      { label: 'Hard Techno', value: 'hard techno' },
      { label: 'House (Old-school)', value: 'house (old-school)' },
      { label: 'Jackin House', value: 'jackin house' },
      { label: 'Latin House', value: 'latin house' },
      { label: 'Lo-fi House', value: 'lo-fi house' },
      { label: 'Melodic Techno & House', value: 'melodic techno & house' },
      { label: 'Minimal House', value: 'minimal house' },
      { label: 'Minimal Techno', value: 'minimal techno' },
      { label: 'Organic House', value: 'organic house' },
      { label: 'Peak / Driving Techno', value: 'peak / driving techno' },
      { label: 'Progressive House', value: 'progressive house' },
      { label: 'Tech House', value: 'tech house' },
      { label: 'Techno', value: 'techno' },
      { label: 'Tribal / Afro House', value: 'tribal / afro house' },
      { label: 'Ambient', value: 'ambient' },
      { label: 'Downtempo', value: 'downtempo' },
      { label: 'Drone', value: 'drone' },
      {
        label: 'Experimental Electronic',
        value: 'experimental electronic',
      },
      { label: 'IDM / Glitch', value: 'idm / glitch' },
      { label: 'Leftfield Bass ', value: 'leftfield bass ' },
      { label: 'Lounge', value: 'lounge' },
      { label: 'Psydub / Psychill', value: 'psydub / psychill' },
      { label: 'Trip-Hop', value: 'trip-hop' },
      { label: 'Black Metal', value: 'black metal' },
      { label: 'Death Metal', value: 'death metal' },
      { label: 'Doom Metal / Sludge', value: 'doom metal / sludge' },
      { label: 'Electronicore', value: 'electronicore' },
      { label: 'Glam / Hair Metal', value: 'glam / hair metal' },
      { label: 'Gothic Metal', value: 'gothic metal' },
      { label: 'Grunge', value: 'grunge' },
      { label: 'Hard Rock', value: 'hard rock' },
      { label: 'Industrial', value: 'industrial' },
      { label: 'Melodic Metal', value: 'melodic metal' },
      { label: 'Metalcore', value: 'metalcore' },
      { label: 'Noise Rock', value: 'noise rock' },
      { label: 'Post-grunge', value: 'post-grunge' },
      { label: 'Post-Metal', value: 'post-metal' },
      {
        label: 'Progressive Metal / Djent',
        value: 'progressive metal / djent',
      },
      { label: 'Rap Metal', value: 'rap metal' },
      { label: 'Screamo', value: 'screamo' },
      { label: 'Stoner Rock', value: 'stoner rock' },
      { label: 'Symphonic Metal', value: 'symphonic metal' },
      { label: 'Thrash Metal', value: 'thrash metal' },
      { label: 'Acapella / Vocal', value: 'acapella / vocal' },
      { label: 'Christian', value: 'christian' },
      { label: 'Comedy', value: 'comedy' },
      { label: 'Holiday Music', value: 'holiday music' },
      {
        label: 'Noise / Harsh Noise Wall',
        value: 'noise / harsh noise wall',
      },
      { label: 'Solo Guitar', value: 'solo guitar' },
      { label: 'Spoken Word', value: 'spoken word' },
      { label: 'Adult Contemporary', value: 'adult contemporary' },
      {
        label: 'Afrobeats / Afro-pop / Afro-fusion',
        value: 'afrobeats / afro-pop / afro-fusion',
      },
      { label: 'Bedroom / Lo-fi Pop', value: 'bedroom / lo-fi pop' },
      { label: 'Commercial', value: 'commercial' },
      { label: 'Dance Pop', value: 'dance pop' },
      { label: 'Dancehall', value: 'dancehall' },
      { label: 'Electro Pop', value: 'electro pop' },
      { label: 'French Pop', value: 'french pop' },
      { label: 'German pop (Schlager)', value: 'german pop (schlager)' },
      { label: 'J-Pop', value: 'j-pop' },
      { label: 'K-Pop', value: 'k-pop' },
      { label: 'Latin Pop', value: 'latin pop' },
      { label: 'Reggaeton', value: 'reggaeton' },
      { label: 'Hardcore Punk', value: 'hardcore punk' },
      { label: 'Pop Punk', value: 'pop punk' },
      { label: 'Post-Hardcore', value: 'post-hardcore' },
      { label: 'Post-Punk', value: 'post-punk' },
      { label: 'Punk', value: 'punk' },
      { label: 'Ska', value: 'ska' },
      { label: 'Skate Punk', value: 'skate punk' },
      {
        label: 'Alternative / Indie R&B',
        value: 'alternative / indie r&b',
      },
      { label: 'Blues', value: 'blues' },
      { label: 'Contemporary R&B', value: 'contemporary r&b' },
      { label: 'Disco', value: 'disco' },
      { label: 'Electro Funk', value: 'electro funk' },
      { label: 'Funk', value: 'funk' },
      { label: 'Neo-Soul', value: 'neo-soul' },
      { label: 'Retro Soul', value: 'retro soul' },
      { label: 'Cumbia', value: 'cumbia' },
      { label: 'Dub', value: 'dub' },
      { label: 'Flamenco', value: 'flamenco' },
      { label: 'Global Bass', value: 'global bass' },
      { label: 'Reggae', value: 'reggae' },
      { label: 'Regional Mexicana', value: 'regional mexicana' },
      { label: 'Salsa', value: 'salsa' },
      { label: 'Tropical', value: 'tropical' },
      { label: 'World Music (African)', value: 'world music (african)' },
      { label: 'World Music (Far East)', value: 'world music (far east)' },
      {
        label: 'World Music (Latin & Hispanic)',
        value: 'world music (latin & hispanic)',
      },
      {
        label: 'World Music (Middle Eastern & North African)',
        value: 'world music (middle eastern & north african)',
      },
      { label: 'World Music (Other)', value: 'world music (other)' },
      {
        label: 'World Music (South Asian)',
        value: 'world music (south asian)',
      },
    ],
  },
]

export const types = [
  {
    label: 'Remix',
    value: 'remix',
  },
  {
    label: 'Cover',
    value: 'cover',
  },
  {
    label: 'Original',
    value: 'original',
  },
]

export const moods_values = [
  {
    label: 'Mood',
    options: [
      {
        value: 'sexy',
        label: 'Sexy',
      },
      {
        value: 'energetic',
        label: 'Energetic',
      },
      {
        value: 'sad',
        label: 'Sad',
      },
      {
        value: 'chill',
        label: 'Chill',
      },
      {
        value: 'romantic',
        label: 'Romantic',
      },
    ],
  },
]
